Adds TypeScript declarations
egoist/vue-prism-component pull request #2
Opened 2018-07-16 13:54 UTC by vatson

Recently, TS is becoming more popular. It would be great if you allow to add support for TypeScript.

2018-10-17 05:26 UTC, egoist commented on types/index.d.ts
> +}
Can you add types for props as well?

2018-11-12 23:27 UTC, vatson commented
@egoist I added prop types, pls check

2019-11-15 13:58 UTC, phildebr commented
Could you please merge this?

2020-04-12 16:56 UTC, mnapoli commented
Would be great to have!

2020-09-29 17:11 UTC, rbclark commented
Unsure if this is still up-to-date but came to this repo explicitly looking for typings for this package, would really be great to see this merged.

2021-05-17 08:23 UTC, Shinigami92 commented
> Unsure if this is still up-to-date but came to this repo explicitly looking for typings for this package, would really be great to see this merged.

Same

2021-05-17 08:26 UTC, Shinigami92 requested changes

2021-05-17 08:26 UTC, Shinigami92 commented on types/index.d.ts
> +  const _default: FunctionalComponentOptions<{
```suggestion
  import { FunctionalComponent } from 'vue';
  const _default: FunctionalComponent<{
```

2021-05-17 08:26 UTC, Shinigami92 commented on types/index.d.ts
> +    language: string;
```suggestion
    code?: string;
    language?: string;
```

2021-07-06 02:43 UTC, elevatebart commented
If this PR is only missing the changes suggested, can @vatson make them so we can merge? 
@egoist, @Shinigami92 what are your suggestions?

I could also fork @vatson repo, do the changes, and create a new PR.

2021-07-06 02:44 UTC, elevatebart commented
This closes #39

2021-08-12 21:14 UTC, closed without merging

2021-08-13 16:24 UTC, Shinigami92 commented
@vatson What's the status of this? Why just closed?

2021-08-13 16:42 UTC, vatson commented
> @vatson What's the status of this? Why just closed?
@Shinigami92 

First, the issue has been stuck for 3 years. I don't see any interest and activity from the maintainer side. All of this tells me that this issue will be here forever.

Second, current `master` branch  is far ahead. It's has already been migrated on vue 3. It makes incompatible code with proposed typings.

I could do typings for both vue 2 and vue 3 with new PRs, but still I'm not sure if the project maintainers are ready to assist and support. It looks like a waste of time to me.

2021-08-13 16:44 UTC, Shinigami92 commented
@vatson In such a case, did you consider https://github.com/DefinitelyTyped/DefinitelyTyped ?